name: firebase_to_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.8.3 <4.0.0"

# DependÃªncias do projeto
dependencies:
  path: ^1.9.0
  http: ^1.5.0
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
